# Generated by Django 6.0.1 on 2026-02-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='like',
        ),
    ]
